[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
padding = { x = 6, y = 6}
#opacity = 0.2
#blur = false
#startup_mode = "Windowed"
#position = { x = 200, y = 200 }



# BEGIN ACE
[colors.primary]
background = "#0C0B0B"
foreground = "#c2c2c2"

[colors.cursor]
text =       "#0C0B0B"
cursor =     "#c2c2c2"

[colors.normal]
black =      "#0C0B0B"
red =        "#B83924"
green =      "#8A756F"
yellow =     "#968479"
blue =       "#7D7E85"
magenta =    "#A59B97"
cyan =       "#C8B8B4"
white =      "#c2c2c2"

[colors.bright]
black =      "#6a5656"
red =        "#B83924"
green =      "#8A756F"
yellow =     "#968479"
blue =       "#7D7E85"
magenta =    "#A59B97"
cyan =       "#C8B8B4"
white =      "#c2c2c2"
# END ACE
