#!/usr/bin/env bash

export XDG_CURRENT_DESKTOP='bspwm'
export _JAVA_AWT_WM_NONREPARENTING=1

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor DP-4 -d VI VII VIII IX X
#bspc monitor DP-6 -d I II III IV V

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

xsetroot -cursor_name left_ptr

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a \* state=floating
bspc rule -a Vivado state=floating
bspc rule -a Thunar state=floating
bspc rule -a libreoffice state=floating


picom &
polybar &
