#!/usr/bin/env bash
source ~/.cache/wal/colors.sh

### AUTOSTART
eval ~/.fehbg &
xrdb -merge ~/.cache/wal/colors.Xresources
picom &
polybar &

export XDG_CURRENT_DESKTOP='bspwm'
export _JAVA_AWT_WM_NONREPARENTING=1

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor DP-4 -d VI VII VIII IX X
#bspc monitor DP-6 -d I II III IV V

bspc config border_width 2
bspc config window_gap 12
bspc config focused_border_color $color1

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Wrapper-2.0 monitor=primary follow=on state=floating border=off rectangle=500x600+0+0

xsetroot -cursor_name left_ptr
bspc config focus_follows_pointer true

bspc rule -a \* state=floating
