[[mgr.prepend_keymap]]
on   = [ "t", "d" ]
run  = "close"
desc = "Close the current tab"

[[mgr.prepend_keymap]]
on   = "'"
run  = "plugin fzfmarks"
desc = "Bookmarks: fuzzy jump"

[[mgr.prepend_keymap]]
on   = [ "b", "a" ]
run  = "plugin fzfmarks add"
desc = "Bookmarks: add current directory"

[[mgr.prepend_keymap]]
on   = [ "b", "A" ]
run  = "plugin fzfmarks add_hovered"
desc = "Bookmarks: add hovered file/dir"

[[mgr.prepend_keymap]]
on   = [ "b", "b" ]
run  = "plugin fzfmarks"
desc = "Bookmarks: fuzzy jump"

[[mgr.prepend_keymap]]
on   = [ "b", "p" ]
run  = "plugin pins"
desc = "Pin/unpin hovered item to the top"

[[mgr.prepend_keymap]]
on   = [ ",", "c" ]
run  = "sort custom --reverse=no"
desc = "Sort with pins on top (default)"
